trigger:
- master  # Ejecuta el pipeline en cada push a main

pool:
  name: 'Default'

steps:
- task: JavaToolInstaller@0
  inputs:
    version: '21'  # Especifica la versión de Java que necesitas
    jdkArchitecture: 'x64'

- script: |
    mvn clean install
  displayName: 'Build and Run Tests'

